name: Build PHAR

on:
  push:

jobs:
  build-phar:
    name: Build PHAR
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ["8.1"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: pmmp/setup-php-action@2.0.0
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
          pm-version-major: "5"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Build PHAR file
        run: composer run-script build

      - uses: actions/upload-artifact@v3
        with:
          name: oh-my-pmmp
          path: oh-my-pmmp.phar