name: Build PHAR

on:
  push:

jobs:
  build-phar:
    name: Build PHAR
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ["8.1"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: pmmp/setup-php-action@2.0.0
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
          pm-version-major: "5"

      - uses: "ramsey/composer-install@v2"
        with:
          working-directory: "vendor-bin/box"
          composer-options: "--ignore-platform-reqs --optimize-autoloader"

      - name: Build PHAR file
        run: |
          wget -O box.phar "https://github.com/box-project/box/releases/download/4.4.0/box.phar"
          php ./box.phar compile

      - uses: actions/upload-artifact@v3
        with:
          name: oh-my-pmmp
          path: oh-my-pmmp.phar