name: Build PHAR

on:
  push:

jobs:
  build-phar:
    name: Build PHAR
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ["8.1"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: phar.readonly=0
          tools: composer
          coverage: none

      - uses: "ramsey/composer-install@v2"
        with:
          working-directory: "vendor-bin/box"
          composer-options: "--ignore-platform-reqs --optimize-autoloader"

      - name: Build PHAR file
        run: composer run-script build

      - uses: actions/upload-artifact@v3
        with:
          name: oh-my-pmmp
          path: oh-my-pmmp.phar